let bribes =[
    {
        "name" : "bribeCops",
        "display" : "Bribe Cops",
        "USDtoHeat" : 1,
        "cooldownSeconds" : 60,
        "unlockCost" : 1e6,
        "unlocked" : true,
        "ready" : true,
        "secondsLeft" : 0,
    },
    {
        "name" : "bribeDetective",
        "display" : "Bribe Detective",
        "USDtoHeat" : 2,
        "cooldownSeconds" : 120,
        "unlockCost" : 1e7,
        "unlocked" : false,
        "ready" : true,
        "secondsLeft" : 0,
    },
    {
        "name" : "bribeJudge",
        "display" : "Bribe Judge",
        "USDtoHeat" : 4,
        "cooldownSeconds" : 240,
        "unlockCost" : 1e8,
        "unlocked" : false,
        "ready" : true,
        "secondsLeft" : 0,
    },
    {
        "name" : "bribeMayor",
        "display" : "Bribe Mayor",
        "USDtoHeat" : 8,
        "cooldownSeconds" : 480,
        "unlockCost" : 1e9,
        "unlocked" : false,
        "ready" : true,
        "secondsLeft" : 0,
    },
    {
        "name" : "bribeGovernor",
        "display" : "Bribe Governor",
        "USDtoHeat" : 16,
        "cooldownSeconds" : 960,
        "unlockCost" : 1e10,
        "unlocked" : false,
        "ready" : true,
        "secondsLeft" : 0,
    },
    {
        "name" : "bribePresident",
        "display" : "Bribe President",
        "USDtoHeat" : 32,
        "cooldownSeconds" : 1920,
        "unlockCost" : 1e11,
        "unlocked" : false,
        "ready" : true,
        "secondsLeft" : 0,
    },
    {
        "name" : "bribeAliens",
        "display" : "Bribe Aliens",
        "USDtoHeat" : 64,
        "cooldownSeconds" : 3840,
        "unlockCost" : 1e12,
        "unlocked" : false,
        "ready" : true,
        "secondsLeft" : 0,
    }
]