let jobs = [
    {
        "name" : "Shoplift",
        "display" : "Shoplift",
        "money" : 1000,
        "work" : 10,
        "worked" : 0, 
        "goonsWorking" : 0,
        "observed" : false,
        "unlocked" : true,
        "unlockCost" : 0,
        "Building" : "Black Market Van",
        "BuildingsOwned" : 0,
        "BuildingCost" : 10000,
        "BuildingIncome" : 100,
    },
    {
        "name" : "Pickpocket",
        "display" : "Pickpocket",
        "money" : 2000,
        "work" : 20,
        "worked" : 0, 
        "goonsWorking" : 0,
        "observed" : false,
        "unlocked" : false,
        "unlockCost" : 1000,
        "Building" : "Coinstar Machine",
        "BuildingsOwned" : 0,
        "BuildingCost" : 20000,
        "BuildingIncome" : 225,
    },
    {
        "name" : "Mugging",
        "display" : "Mugging",
        "money" : 5000,
        "work" : 50,
        "worked" : 0, 
        "goonsWorking" : 0,
        "observed" : false,
        "unlocked" : false,
        "unlockCost" : 5000,
        "Building" : "Alleyway",
        "BuildingsOwned" : 0,
        "BuildingCost" : 50000,
        "BuildingIncome" : 600,
    },
    {
        "name" : "Hotwire",
        "display" : "Hotwire",
        "money" : 10000,
        "work" : 100,
        "worked" : 0, 
        "goonsWorking" : 0,
        "observed" : false,
        "unlocked" : false,
        "unlockCost" : 10000,
        "Building" : "Dealership",
        "BuildingsOwned" : 0,
        "BuildingCost" : 100000,
        "BuildingIncome" : 1400,
    },
]