let jobs = [
    {
        "name" : "Shoplift",
        "display" : "Shoplift",
        "money" : 1000,
        "work" : 10,
        "worked" : 0, 
        "goonsWorking" : 0,
        "observed" : false,
        "unlocked" : true,
        "unlockCost" : 0,
    },
    {
        "name" : "Pickpocket",
        "display" : "Pickpocket",
        "money" : 2000,
        "work" : 20,
        "worked" : 0, 
        "goonsWorking" : 0,
        "observed" : false,
        "unlocked" : false,
        "unlockCost" : 1000,
    },
    {
        "name" : "Mugging",
        "display" : "Mugging",
        "money" : 5000,
        "work" : 50,
        "worked" : 0, 
        "goonsWorking" : 0,
        "observed" : false,
        "unlocked" : false,
        "unlockCost" : 5000,
    },
    {
        "name" : "Hotwire",
        "display" : "Hotwire",
        "money" : 10000,
        "work" : 100,
        "worked" : 0, 
        "goonsWorking" : 0,
        "observed" : false,
        "unlocked" : false,
        "unlockCost" : 10000,
    },
]