var player = {
    name: "Stringer Bell",
    workOnPersonalCrime: 10,
    managementMultiplier: 0.1,
    goonDiscount: 1,
    USD: 0,
    energy: 100,
    energyMax: 100,
    energyRegenPerSecond: 1,
    criminalCareerStage: "Street Level",
    goonsFree: 0,
    goonsImprisoned: 0,
    goonsTotal: 0,
    goonPrice: 0,
    observing: 0,
    observeMax: 1,
    nextJobCost: 0,
    nextJobName: " ",
    goonX: 1,
    timesShoplifted: 0,
    hasSaved : false,
    version : "Alpha 0.0.2"
};